export const rawFiles = [
  {
    id: "id::pkg7/1",
    path: ["id::pkg7", "id::pkg7/1"],
    instrument: "GBP A 3M SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-05-24",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 4.1,
  },
  {
    id: "pkg4",
    path: ["id::pkg4"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "MARKIT",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::solo-5",
    path: ["id::solo-5"],
    instrument: "USD A 6M SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-23",
    source: "MARKIT",
    strategy: "IRS Curve",
    status: "Missed",
    clientSide: "RECEIVE",
    sizeMM: 6.6,
  },
  {
    id: "id::pkg2/2",
    path: ["id::pkg2", "id::pkg2/2"],
    instrument: "USD A 6M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-30",
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: "Missed",
    clientSide: "RECEIVE",
    sizeMM: 7.9,
  },
  {
    id: "id::pkg8/2",
    path: ["id::pkg8", "id::pkg8/2"],
    instrument: "EUR A 1Y ESTR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-06-17",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 9.5,
  },
  {
    id: "pkg3",
    path: ["id::pkg3"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::solo-9",
    path: ["id::solo-9"],
    instrument: "USD A 2Y EURIBOR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-27",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 2.3,
  },
  {
    id: "id::pkg5/1",
    path: ["id::pkg5", "id::pkg5/1"],
    instrument: "USD A 6M ESTR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-08",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 6.8,
  },
  {
    id: "id::pkg9/1",
    path: ["id::pkg9", "id::pkg9/1"],
    instrument: "GBP A 3M SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-04",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "RECEIVE",
    sizeMM: 1.5,
  },
  {
    id: "id::pkg6/3",
    path: ["id::pkg6", "id::pkg6/3"],
    instrument: "USD A 6M ESTR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-16",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 3.1,
  },
  {
    id: "id::pkg7/3",
    path: ["id::pkg7", "id::pkg7/3"],
    instrument: "USD A 2Y ESTR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-13",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "PAY",
    sizeMM: 9.3,
  },
  {
    id: "id::solo-7",
    path: ["id::solo-7"],
    instrument: "GBP A 2Y SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-11",
    source: "MARKIT",
    strategy: "IRS Fly",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 4.7,
  },
  {
    id: "id::pkg8/3",
    path: ["id::pkg8", "id::pkg8/3"],
    instrument: "USD A 2Y SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-31",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 2.0,
  },
  {
    id: "id::pkg10/2",
    path: ["id::pkg10", "id::pkg10/2"],
    instrument: "USD A 3M SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-09",
    source: "TRADEWEB",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 5.4,
  },
  {
    id: "pkg5",
    path: ["id::pkg5"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "MARKIT",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "pkg10",
    path: ["id::pkg10"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "TRADEWEB",
    strategy: "IRS Fly",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::pkg6/1",
    path: ["id::pkg6", "id::pkg6/1"],
    instrument: "USD A 1Y SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-19",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 7.4,
  },
  {
    id: "id::solo-11",
    path: ["id::solo-11"],
    instrument: "GBP A 3M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-05",
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: "Not Traded",
    clientSide: "PAY",
    sizeMM: 7.8,
  },
  {
    id: "id::solo-3",
    path: ["id::solo-3"],
    instrument: "GBP A 2Y EURIBOR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-08",
    source: "TRADEWEB",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 6.3,
  },
  {
    id: "id::solo-6",
    path: ["id::solo-6"],
    instrument: "GBP A 6M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-21",
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 2.8,
  },
  {
    id: "pkg9",
    path: ["id::pkg9"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "MARKIT",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "pkg2",
    path: ["id::pkg2"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "pkg7",
    path: ["id::pkg7"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::pkg8/1",
    path: ["id::pkg8", "id::pkg8/1"],
    instrument: "GBP A 6M SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-06",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 8.1,
  },
  {
    id: "id::solo-4",
    path: ["id::solo-4"],
    instrument: "USD A 2Y EURIBOR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-14",
    source: "MARKIT",
    strategy: "IRS Curve",
    status: "Not Traded",
    clientSide: "PAY",
    sizeMM: 8.8,
  },
  {
    id: "id::solo-8",
    path: ["id::solo-8"],
    instrument: "GBP A 2Y ESTR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-05-30",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 1.4,
  },
  {
    id: "id::solo-13",
    path: ["id::solo-13"],
    instrument: "GBP A 6M ESTR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-05-26",
    source: "TRADEWEB",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 1.0,
  },
  {
    id: "id::pkg9/2",
    path: ["id::pkg9", "id::pkg9/2"],
    instrument: "GBP A 2Y SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-03",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 6.7,
  },
  {
    id: "id::solo-12",
    path: ["id::solo-12"],
    instrument: "EUR A 3M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-05-28",
    source: "TRADEWEB",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 7.1,
  },
  {
    id: "id::pkg5/2",
    path: ["id::pkg5", "id::pkg5/2"],
    instrument: "GBP A 1Y ESTR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-05-30",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 5.1,
  },
  {
    id: "id::pkg4/2",
    path: ["id::pkg4", "id::pkg4/2"],
    instrument: "GBP A 1Y SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-08",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 3.5,
  },
  {
    id: "id::pkg10/3",
    path: ["id::pkg10", "id::pkg10/3"],
    instrument: "EUR A 1Y ESTR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-05-30",
    source: "TRADEWEB",
    strategy: "IRS Fly",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 2.2,
  },
  {
    id: "id::pkg10/1",
    path: ["id::pkg10", "id::pkg10/1"],
    instrument: "EUR A 6M SOFR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-06-03",
    source: "TRADEWEB",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 4.8,
  },
  {
    id: "id::pkg4/1",
    path: ["id::pkg4", "id::pkg4/1"],
    instrument: "USD A 3M SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-17",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 1.3,
  },
  {
    id: "pkg1",
    path: ["id::pkg1"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::solo-1",
    path: ["id::solo-1"],
    instrument: "USD A 6M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-22",
    source: "BLOOMBERG",
    strategy: "IRS Curve",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 6.1,
  },
  {
    id: "id::solo-10",
    path: ["id::solo-10"],
    instrument: "USD A 6M SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-11",
    source: "MARKIT",
    strategy: "IRS Fly",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 4.7,
  },
  {
    id: "id::pkg3/2",
    path: ["id::pkg3", "id::pkg3/2"],
    instrument: "GBP A 2Y EURIBOR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-01",
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 3.8,
  },
  {
    id: "id::pkg1/1",
    path: ["id::pkg1", "id::pkg1/1"],
    instrument: "GBP A 6M SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-11",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "RECEIVE",
    sizeMM: 5.7,
  },
  {
    id: "id::solo-2",
    path: ["id::solo-2"],
    instrument: "GBP A 1Y SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-20",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 4.6,
  },
  {
    id: "pkg8",
    path: ["id::pkg8"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "MARKIT",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::pkg9/3",
    path: ["id::pkg9", "id::pkg9/3"],
    instrument: "EUR A 6M ESTR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-06-21",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "PAY",
    sizeMM: 2.7,
  },
  {
    id: "id::pkg2/1",
    path: ["id::pkg2", "id::pkg2/1"],
    instrument: "GBP A 2Y SOFR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-05-23",
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 6.2,
  },
  {
    id: "id::pkg1/3",
    path: ["id::pkg1", "id::pkg1/3"],
    instrument: "USD A 2Y ESTR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-16",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "RECEIVE",
    sizeMM: 9.7,
  },
  {
    id: "id::pkg1/2",
    path: ["id::pkg1", "id::pkg1/2"],
    instrument: "GBP A 6M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-06-15",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 5.8,
  },
  {
    id: "pkg6",
    path: ["id::pkg6"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "MARKIT",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "id::pkg7/2",
    path: ["id::pkg7", "id::pkg7/2"],
    instrument: "USD A 1Y SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-29",
    source: "BLOOMBERG",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 8.5,
  },
  {
    id: "id::pkg6/2",
    path: ["id::pkg6", "id::pkg6/2"],
    instrument: "USD A 3M SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-22",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 1.2,
  },
  {
    id: "id::pkg3/1",
    path: ["id::pkg3", "id::pkg3/1"],
    instrument: "USD A 6M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-19",
    source: "BLOOMBERG",
    strategy: "IRS Fly",
    status: "Not Traded",
    clientSide: "PAY",
    sizeMM: 5.3,
  },
  {
    id: "id::pkg4/3",
    path: ["id::pkg4", "id::pkg4/3"],
    instrument: "GBP A 6M ESTR",
    product: "IRS Fixed Float",
    ccy: "GBP",
    startDate: "2025-05-24",
    source: "MARKIT",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 8.2,
  },
];
