export const rawFiles = [
  {
    id: "pkg1",
    path: ["pkg1"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "WEB",
    strategy: "IRS Outright",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "pkg1/1",
    path: ["pkg1", "pkg1/1"],
    instrument: "USD A 1Y SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-05-22",
    source: "WEB",
    strategy: "IRS Outright",
    status: "Not Traded",
    clientSide: "RECEIVE",
    sizeMM: 2.0,
  },
  {
    id: "pkg1/2",
    path: ["pkg1", "pkg1/2"],
    instrument: "USD A 2Y SOFR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-05-23",
    source: "WEB",
    strategy: "IRS Outright",
    status: "Done",
    clientSide: "PAY",
    sizeMM: 5.0,
  },
  {
    id: "pkg2",
    path: ["pkg2"],
    instrument: null,
    product: null,
    ccy: null,
    startDate: null,
    source: "WORLD",
    strategy: "IRS Fly",
    status: null,
    clientSide: null,
    sizeMM: null,
  },
  {
    id: "pkg2/1",
    path: ["pkg2", "pkg2/1"],
    instrument: "EUR A 6M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-05-24",
    source: "WORLD",
    strategy: "IRS Fly",
    status: "Missed",
    clientSide: "PAY",
    sizeMM: 3.5,
  },
  {
    id: "pkg2/2",
    path: ["pkg2", "pkg2/2"],
    instrument: "EUR A 1Y ESTR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-05-25",
    source: "WORLD",
    strategy: "IRS Fly",
    status: "Done",
    clientSide: "RECEIVE",
    sizeMM: 7.0,
  },
  // ✅ Flat item not in a package
  {
    id: "solo-1",
    path: ["solo-1"],
    instrument: "EUR A 3M EURIBOR",
    product: "IRS Fixed Float",
    ccy: "EUR",
    startDate: "2025-06-01",
    source: "WEB",
    strategy: "IRS Curve",
    status: "Not Traded",
    clientSide: "PAY",
    sizeMM: 4.0,
  },
  {
    id: "solo-2",
    path: ["solo-2"],
    instrument: "USD A 1Y SOFR",
    product: "IRS Fixed Float",
    ccy: "USD",
    startDate: "2025-06-02",
    source: "WORLD",
    strategy: "IRS Outright",
    status: "Missed",
    clientSide: "RECEIVE",
    sizeMM: 3.2,
  },
];
